// <auto-generated/>
using Npgsql;
using NpgsqlTypes;
using System;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace DistributedOutbox.Postgres.Queries
{
    // ReSharper disable once PartialTypeWithSinglePart
    public partial class UpdateStatusWithMetadataQuery
    {
        private string _cachedSql;
        private readonly object _cachedSqlLocker = new object();

        /// <summary>
        /// Заготовка для определенной пользователем пост-обработки текста запроса
        /// </summary>
        /// <param name="queryText">Текст кэшированного sql-запроса</param>
        partial void ProcessCachedSql(ref string queryText);

        /// <summary>
        /// Возвращает текст запроса
        /// </summary>
        /// <returns>Текст запроса</returns>
        protected virtual string GetQueryText()
        {
            if (_cachedSql == null)
            {
                lock (_cachedSqlLocker)
                {
                    using (Stream stream = typeof(UpdateStatusWithMetadataQuery).Assembly.GetManifestResourceStream("DistributedOutbox.Postgres.Queries.UpdateStatusWithMetadataQuery.sql"))
                    {
                        string sql = new StreamReader(stream ?? throw new InvalidOperationException("Can not get manifest resource stream.")).ReadToEnd();

                        const string sectionRegexPattern = @"--\s*begin\s+[a-zA-Z0-9_]*\s*\r?\n.*?\s*\r?\n\s*--\s*end\s*\r?\n";
                        const RegexOptions regexOptions = RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled;
                        sql = Regex.Replace(sql, sectionRegexPattern, string.Empty, regexOptions);

                        _cachedSql = sql;

                        ProcessCachedSql(ref _cachedSql);
                    }
                }
            }

            return _cachedSql;
        }

        /// <summary>
        /// Добавляет параметр к команде
        /// </summary>
        /// <param name="command">Команда SQL</param>
        /// <param name="parameterType">Тип параметра</param>
        /// <param name="parameterName">Имя параметра</param>
        /// <param name="value">Значение параметра</param>
        /// <param name="length">Длина параметра</param>
        protected virtual void AddParameter(IDbCommand command, NpgsqlDbType parameterType, string parameterName, object value, int? length = null)
        {
            var parameter = new NpgsqlParameter
            {
                ParameterName = parameterName,
                NpgsqlDbType = parameterType,
                Value = value ?? DBNull.Value
            };

            if (length.HasValue && length.Value > 0)
            {
                parameter.Size = length.Value;
            }
    
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Выполняет обновление строк в таблице
        /// </summary>
        /// <param name="connection">Подключение к БД</param>
        /// <param name="status">status</param>
        /// <param name="metadata">metadata</param>
        /// <param name="eventId">eventId</param>
        /// <param name="cancellationToken">Токен отмены</param>
        /// <returns>Количество измененных строк</returns>
        public virtual async Task<int> UpdateAsync(DbConnection connection, string status, string metadata, long? eventId, CancellationToken cancellationToken)
        {
            using(DbCommand cmd = connection.CreateCommand())
            {
                cmd.CommandText = GetQueryText();
                AddParameter(cmd, NpgsqlDbType.Text, "@status", status);
                AddParameter(cmd, NpgsqlDbType.Jsonb, "@metadata", metadata);
                AddParameter(cmd, NpgsqlDbType.Bigint, "@eventId", eventId);

                PrepareCommand(cmd);
                return await cmd.ExecuteNonQueryAsync(cancellationToken);
            }
        }

        /// <summary>
        /// Заготовка для определенной пользователем обработки команды перед исполнением
        /// </summary>
        /// <param name="command">Команда</param>
        partial void PrepareCommand(IDbCommand command);
    }
}